steps:
  - name: gcr.io/cloud-builders/gcloud
    args: 
    - |
      compute ssh leo_cuvelier@eu-west1crapo-prod --zone=europe-west1-b --project=crapo-348812 --command="\
      cd crapo \
      git pull \
      "
