steps:
  - name: gcr.io/cloud-builders/gcloud
    args: ['compute', 'ssh', 'eu-west1crapo-prod','--zone=europe-west1-b', '--command="cd /home/leo_cuvelier/crapo && git pull"', '--project=crapo-348812' ]
